<?php include 'header.php';?> <!-- include header in credits page -->

<main class="container">
<section class="card">
<h2>Who this webpage Owes its Existence to</h2>
<p>This page acknowledges the external resources that supported the development of the Deck of Many Proteins tool.</p>
</section>

<section class="card">
<h2>W3Schools</h2>
<p>W3Schools was used for learning the PHP, PDO, SQL, CSS, and Apache basics. W3Schools made this project possible, as it is a central store of programming examples, exercises, troubleshooting help and other information.</p>
</section>

<section class="card">
<h2>Stack Overflow</h2>
<p>Stack Overflow was used for more specific trouble shooting. When I couldn't understand/interpret bash/sql/php errors, Stack Overflow was the first (and usually last) place I looked for folks who had similar issues to the ones I was having.</p>
</section>

<section class="card">
<h2>The NCBI</h2>
<p>Deck of Many Proteins is directly powered by data stored at and tools developed by the NCBI, particularly by the Entrez Direct suite of tools, and the many protein databases said suite has access to.</p>
</section>

<section class="card">
<h2>EMBL-EBI</h2>
<p>Deck of many proteins also utilizes EMBL-EBI's Clustal Omega tool to generate multiple sequence alignments for downstream conservation analyses with plotcon.</p>
</section>

<section class="card">
<h2>EMBOSS</h2>
<h3>Plotcon</h3>
<p>Deck of Many Proteins utilizes EBMOSS' Plotcon tool for visualization of the conservation captured in the MSAs generated by Clustal Omega.</p>
<h3>patmatmotifs</h3>
<p> Deck of Many Proteins utilizes EMBOSS' patmatmotifs tool for detection of motifs in sequences returned by the Entrez Direct queries.</p>
</section>


<section class="card">
<h2>GitHub</h2>
<p>GitHub was used for version control. As most know, it as an industry standard for version management and general safe back-up practice. Github was used to host the remote repository that corresponds to the code that this webpage uses, along with some test scripts that don't run on the webpage directly.</p>
</section>

<section class="card">
<h2>ChatGPT</h2>
<p>ChatGPT was used when stack overflow failed at debugging PHP, PDO, CSS, and MySQL errors. It was also used to suggest improvements to my MySQL schema design, draft code for the interactive parts of the pipeline (submit.php, job.php, history, help, and credits, and to troubleshoot tricky permission errors I had with all of the scripts I was making.</p>
</section>

<section class="card">
<h2>Additional Non-Technical Support</h2>
<p>Additional non-technical support: One kickass divorced-dad-rock playlist</p>
</section>
<?php include 'footer.php'; ?> <!-- include footer in credits page -->
